# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install apache-beam[gcp]
    - name: Add PYTHONPATH
      run: |
        DIR=$PWD/..
        if [ -n "$ZSH_VERSION" ]; then
          SHELL_SCRIPT_PATH=~/.zshrc_
        elif [ -n "$BASH_VERSION" ]; then
          SHELL_SCRIPT_PATH=~/.bash_profile
        fi
        echo "PYTHONPATH=$DIR" >> SHELL_SCRIPT_PATH
        echo "export PYTHONPATH" >> SHELL_SCRIPT_PATH
        source SHELL_SCRIPT_PATH
    - name: Create a Symlink
      run: |
        ln -s src/ ../wfa_planning_evaluation_framework
    - name: Test with unittest
      run: |
        find src/ | egrep ".*tests/.*.py" | xargs -n 1 python3
